
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

logger:
  default: info
  logs:
    homeassistant.components.sftp_storage: debug
    homeassistant.components.backup: debug
    asynchssh: debug

sensor:
  - platform: mqtt
    name: "BirdPi Raw Detections"
    state_topic: "raw_detections"
    value_template: "{{ value_json.common }}"
    json_attributes_topic: "birdpi/raw_detections"
    json_attributes_template: >
      {
        "confidence": "{{ value_json.confidence }}",
        "scientific_name": "{{ value_json.scientific }}"
      }
