substitutions:
  device_name: air-quality-pms-1
  friendly_name: "Air Quality FR"
  comment: "Air Quality Sensor (PMS) in Family Room"
  log_level: WARN

packages:
  hardware: !include packages/air-quality-pms-base.yaml
