substitutions:
  device_name: air-quality-pms-2
  friendly_name: "Air Quality DWR"
  comment: "Air Quality Sensor (PMS) in Duane Workroom"
  log_level: WARN

packages:
  hardware: !include packages/air-quality-pms-base.yaml
