substitutions:
  friendly_name: "Temperature Sensor Attic"

esphome:
  name: tempsense1
  friendly_name: ${friendly_name}
  comment: "Standalone Semperature Sensor in Middle of the Attic"
  on_boot:
      priority: 800
      then:
        - wifi.disable:
        - output.turn_off: rf_switch_power
        - delay: 100ms
        - switch.turn_on: antenna_select
        - wifi.enable:

esp32:
  board: seeed_xiao_esp32c6
  variant: ESP32C6
  framework:
    type: esp-idf

logger:
  level: WARN

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${friendly_name}
    password: !secret wifi_ap_password
  power_save_mode: none

captive_portal:

web_server:
  port: 80

output:
  - platform: gpio
    pin: GPIO3
    id: rf_switch_power

switch:
  - platform: gpio
    pin: GPIO14
    id: antenna_select
    restore_mode: ALWAYS_OFF 
    name: "External Wifi Antenna On/Off"

time:
  - platform: homeassistant
    id: esptime

one_wire:
  - platform: gpio
    pin: GPIO21

sensor:
  - platform: wifi_signal
    id: wifi_rssi
    name: "${friendly_name} WiFi Signal"
    update_interval: 60s
  - platform: dallas_temp
    address: 0xf3000000075c9228
    state_class: "measurement"
    unit_of_measurement: "Â°C"
    name: "Attic Temp Sensor"
    id: c_temp
    update_interval: 60s
